### ISSUE TITLE
How to align the RGB and Depth?

### ISSUE THREAD

**Issue by JingKangSun** [Kinovarobotics/ros_kortex_vision#9] opened 2022-03-29 08:52 UTC
Hi,

The result in RVIZ shows that RGB and Depth seem not align properly. 

![rvizpic](https://github.com/JingKangSun/video/blob/main/kk.png)

I have tried to modify the "camera_depth_tf_publisher"  arg in kinova_vision_rgbd.launch. However,  this doesn't work.

This problem has been bothering me for a long time. How can I resolve it?

Thanks!

**Comment by felixmaisonneuve** [comment] 2022-04-04 14:01
Hi @JingKangSun,

This is a duplicate of #1 (in which you commented)

I will close this one and do my best to answer you in the other issue

**Closed as completed by felixmaisonneuve** 2022-04-04 14:01 UTC
